name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint and check types
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: npm install

      - name: Check types
        run: npm run typecheck && npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: npm install

      - name: Test
        run: npm run test

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: npm install

      - name: Build
        run: npm run build
